version: '3.8'
services:
    poi_db:
        container_name: poi_db
        image: postgres:15.1
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 5432:5432
        env_file: 
            - .env
        volumes: 
            - db:/var/lib/postgresql/data
        
volumes:
    db:
        driver: local
    dbdata: